[package]
name = "maru-batu-game-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"

tokio = { version = "1", features = ["rt-multi-thread", "macros"] }

serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }


tracing = "0.1"
tracing-subscriber = "0.3"
